Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

  nodes = {
    "jenkins" => "192.168.56.10",
    "k8s-master" => "192.168.56.11",
    "k8s-worker" => "192.168.56.12"
  }

  nodes.each do |name, ip|
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network "private_network", ip: ip

      node.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
      end

      node.vm.provision "shell", inline: <<-SHELL
        sudo apt update -y
        sudo apt install -y curl wget git
      SHELL
    end
  end
end
