pipeline {
    agent any

    tools {
        nodejs 'node18'
    }

    environment {
        DOCKER_IMAGE = "angelbista/chatbot-ui"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                  cd Chatbot-UI
                  npm install
                '''
            }
        }

        stage('Build Application') {
            steps {
                sh '''
                  cd Chatbot-UI
                  npm run build
                '''
            }
        }

        stage('Docker Build') {
            steps {
                sh '''
                  docker build -t $DOCKER_IMAGE:latest -f docker/Dockerfile .
                '''
            }
        }

        stage('Docker Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                      echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                      docker push $DOCKER_IMAGE:latest
                    '''
                }
            }
        }
    }
}
